name: CI Test for Webhook

on:
    push:
        branches:
            - main

jobs:
    test-webhook:
        runs-on: ubuntu-latest
        steps:
            - name: Run a test step
              run: echo "Action is running, webhook should be triggered!"
